// Steg 1. Importera ReactDOM...
import ReactDOM from 'react-dom';
// Importera vår App.jsx komponent
import App from './App';

// Steg 2. Tala om var vi skall placera vår html(komponent)...
// ReactDOM.render(vad, vart) metoden tar två argument: 1 vad skall renderas och 2 vart skall vi placera det som renderas...
ReactDOM.render(<App />, document.querySelector('#root'));
