const vehicleData = [
  {
    registrationNumber: 'ABC123',
    make: 'Toyota',
    model: 'Yaris',
    color: 'Silver metallic',
    modelYear: 2011,
    mileage: 89750,
    fuelType: 'Bensin',
    gearType: 'Manuell',
    numberOfDoors: 4,
    numberOfGears: 5,
    numberOfSeats: 4,
    enginePower: '125Hk',
    isImported: false,
    value: 0,
    imageUrl: 'no-image.png',
    description: '',
  },
  {
    registrationNumber: 'XYZ334',
    make: 'Volkswagen',
    model: 'Tiguan',
    color: 'Mörkblå',
    modelYear: 2020,
    mileage: 15000,
    fuelType: 'Bensin',
    gearType: 'Automat',
    numberOfDoors: 5,
    numberOfGears: 6,
    numberOfSeats: 5,
    enginePower: '150Hk',
    isImported: false,
    value: 0,
    imageUrl: 'no-image.png',
    description: '',
  },
  {
    registrationNumber: 'GHI789',
    make: 'Volvo',
    model: 'V60',
    color: 'Svart',
    modelYear: 2019,
    mileage: 12000,
    fuelType: 'Bensin',
    gearType: 'Automat',
    numberOfDoors: 5,
    numberOfGears: 6,
    numberOfSeats: 5,
    enginePower: '270Hk',
    isImported: false,
    value: 0,
    imageUrl: 'no-image.png',
    description: '',
  },
  {
    registrationNumber: 'DEF456',
    make: 'Volvo',
    model: 'V90',
    color: 'Mineral vit',
    modelYear: 2017,
    mileage: 45900,
    fuelType: 'Diesel',
    gearType: 'Automat',
    numberOfDoors: 4,
    numberOfGears: 6,
    numberOfSeats: 5,
    enginePower: '250Hk',
    isImported: false,
    value: 0,
    imageUrl: 'no-image.png',
    description: '',
  },
];

export default vehicleData;
